# .github/workflows/single-stage.yml

name: Main Action 

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install node packages
        run: npm install
      - name: run the linter
        run: ./node_modules/.bin/eslint .
  AvaUnitTest:
    runs-on: ubuntu-latest
	steps:
	  - uses: actions/checkout@v2
	  - name: Use NodeJS
	    uses: actions/setup-node@v1
		with:
		  node-version: 14.x
	  - name: Install ava testing tool
	    run: npm install
	  - name: run the test
	    run: npm test
    